### ISSUE TITLE
在win11安装完成之后打开主界面，随便点一个歌单就报错，然后软件就卡死没有反应了

### ISSUE THREAD

**Issue by sunshineluo** [GuMengYu/i-player#48]
**Describe the bug**

**To Reproduce**
1. 
2. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - Version [e.g. v2.0.8]

**Comment by GuMengYu** [comment]
先登录呢

**Comment by sunshineluo** [comment]
登陆之后倒是可以了，不登录的话就会报错，谢谢大佬提点

**Comment by GuMengYu** [comment]
好的 后面我修一下

sunshineluo ***@***.***> 于2023年11月1日周三 12:58写道：
